# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 88fbfd647826a39aeafbb32a2b5f710f5cd16ab78e4d61ebbd2b03898b207ed5c99d7165dbb72a82c24be014a3b6f908c509c3f76f7bfcb133394b626df6c3fd

test:
  secret_key_base: 68b07120fd3cde6243021523e9ed24f23f26e27125a8a116b4efadc59fde7eda3cdb8f6eecd3d952cdf0f3e2f8f240a92c228f9e21575498bdc30bd6ee8d5a81

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
